    - name: install apache
      apt:
        name: apache2
        state: present

    - name: install php
      apt:
        name: php
        state: present
    
    - name: install php-mysql
      apt:
        name: php-mysql
        state: present
